### PR TITLE
Add appendix with component algorithm references

### PR DESCRIPTION
**Pull request by janklaussner**
* appendix with references of signature, curves and hashes
* updated section 'Algorithm Identifiers' with reference to appendix and IDs of component algorithms
* updated algorithm description for signature generation and verification to use Domain separator

### CODE REVIEW

**Comment by ounsworth** [comment]
I think this is a good start, but since these are fixed values, I think we should actually provide HEX DER encoded AlgorithmIDs for each row, then there is absolutely no ambiguity.

**Comment by ounsworth** [comment]
Also, once we have this sorted out here, we will need to do the same in composite-kems: https://github.com/lamps-wg/draft-composite-kem/issues/20

**Comment by janklaussner** [comment]
> I think this is a good start, but since these are fixed values, I think we should actually provide HEX DER encoded AlgorithmIDs for each row, then there is absolutely no ambiguity.

You mean in the appendix? These values are not fed into the signature, they just help to identify the component algorithm used. Is your point that providing DER OID values instead of ASN.1 OIDs helps the implementer with this?

**Comment by johngray-dev** [comment]
@ounsworth  I don't understand why we would need to put hex encodings of the OIDS for the component signatures.  They are not used during the signature computation process.   We already hex encode the composite OIDs themselves which is a representation of the entire composite algorithm.  I think what Jan has here is fine.

**Review by ounsworth — APPROVED** [review]

**Pull request merged**
