### PR TITLE
Updated ASN.1 module as per Carl's suggestion

### LINKED ISSUE #9: ML-DSA public keys should be unwrapped BIT STRINGS with no ASN.1 typing
See on-list discussion: https://mailarchive.ietf.org/arch/msg/spasm/oH68LMpwXtpvltK2PnQSCUO9s0k/

I see that draft-ietf-lamps-dilithium-certificates-03 does this:

~~~
  pk-MLDSA PUBLIC-KEY ::= {
    IDENTIFIER id-MLDSA
    -- KEY no ASN.1 wrapping --
    PARAMS ARE absent
    CERT-KEY-USAGE { nonRepudiation, digitalSignature,
                    keyCertSign, cRLSign }
    --- PRIVATE-KEY no ASN.1 wrapping --
  }
~~~

### PR DESCRIPTION
**Pull request by ounsworth**
Closes #9

### CODE REVIEW

**Comment by ounsworth** [comment]
We need to add a 3rd version of EcCompositeSignaturePublicKey called EdCompositeSignaturePublicKey because EdDSA public keys are not EcPoint. See #48

**Comment by johngray-dev** [comment]
closes #20

**Comment by ounsworth** [comment]
Closes #48

**Comment by ounsworth** [comment]
I checked that the ASN.1 module compiles in asn.1 playground.

**Comment by janklaussner** [comment]
Closes #48

**Pull request merged**
